//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace operatorok.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("operatorok.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 mod 265
        ///780 / 114
        ///814 div 200
        ///470 - 531
        ///802 * 553
        ///766 @ 767
        ///914 / 21
        ///973 mod 642
        ///314 - 372
        ///244 div 227
        ///796 mod 702
        ///790 * 768
        ///821 + 244
        ///444 / 638
        ///66 mod 399
        ///566 mod 59
        ///506 mod 933
        ///831 - 438
        ///474 / 16
        ///623 * 280
        ///742 / 25
        ///973 mod 646
        ///829 + 31
        ///785 div 623
        ///523 * 88
        ///383 div 888
        ///243 mod 544
        ///312 mod 223
        ///293 div 503
        ///264 - 830
        ///751 - 672
        ///963 mod 0
        ///613 + 135
        ///752 mod 687
        ///28 mod 756
        ///309 - 706
        ///350 + 620
        ///128 * 718
        ///736 * 831
        ///801 mod 708
        ///143 / 697
        ///200 + 745
        ///951 / 767
        ///88 mod 813
        ///752 * 10
        ///856 - 16
        ///467 div 656
        ///796 div 223
        ///209 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string kifejezesek {
            get {
                return ResourceManager.GetString("kifejezesek", resourceCulture);
            }
        }
    }
}
